workflows:
  android-workflow:
    name: Android Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    
    environment:
      java: 21
      node: 22
      vars:
        PACKAGE_NAME: "com.phantom.cvstracker"
      
    scripts:
      - name: Install npm dependencies
        script: npm install
        
      - name: Add Android platform
        script: npx cap add android || true
        
      - name: Sync Capacitor
        script: npx cap sync android
        
      - name: Set Android SDK location
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > android/local.properties
          
      - name: Build Android APK (Debug)
        script: |
          cd android
          chmod +x ./gradlew
          ./gradlew assembleDebug
          
    artifacts:
      - android/app/build/outputs/apk/debug/*.apk
